language: node_js
node_js: "10.15"
cache: yarn

stages:
  - name: test

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

  # - name: staging-started
  #   if: tag is present
  # - name: staging
  #   if: tag is present
  # - name: staging-finished
  #   if: tag is present

jobs:
  include:
    - stage: test
      env: [NODE_ENV=test]

    - stage: production-started
      name: Deployment Started
      script: npx @parameter1/base-cms-website-deployment-tool notify-started
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-njflm]

    # - stage: staging-started
    #   name: Deployment Started
    #   script: npx @parameter1/base-cms-website-deployment-tool notify-started
    #   install: skip
    #   env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    #############################
    ### vvv ADD SITES HERE vvv ##
    #############################

    - stage: production
      name: hearthubs.org
      script: npx @parameter1/base-cms-website-deployment-tool deploy hearthubs.org websites
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-njflm]

    # - stage: staging
    #   name: hearthubs.org
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy hearthubs.org websites
    #   install: skip
    #   env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: qcor.hub.heart.org
      script: npx @parameter1/base-cms-website-deployment-tool deploy qcor.hub.heart.org websites
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-njflm]

    # - stage: staging
    #   name: qcor.hub.heart.org
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy qcor.hub.heart.org websites
    #   install: skip
    #   env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: bcvs.hub.heart.org
      script: npx @parameter1/base-cms-website-deployment-tool deploy bcvs.hub.heart.org websites
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-njflm]

    # - stage: staging
    #   name: bcvs.hub.heart.org
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy bcvs.hub.heart.org websites
    #   install: skip
    #   env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: vasculardiscovery.hub.heart.org
      script: npx @parameter1/base-cms-website-deployment-tool deploy vasculardiscovery.hub.heart.org websites
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-njflm]

    # - stage: staging
    #   name: vasculardiscovery.hub.heart.org
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy vasculardiscovery.hub.heart.org websites
    #   install: skip
    #   env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: hypertension.hub.heart.org
      script: npx @parameter1/base-cms-website-deployment-tool deploy hypertension.hub.heart.org websites
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-njflm]

    # - stage: staging
    #   name: hypertension.hub.heart.org
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy hypertension.hub.heart.org websites
    #   install: skip
    #   env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: sessions.hub.heart.org
      script: npx @parameter1/base-cms-website-deployment-tool deploy sessions.hub.heart.org websites
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-njflm]

    # - stage: staging
    #   name: sessions.hub.heart.org
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy sessions.hub.heart.org websites
    #   install: skip
    #   env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: isc.hub.heart.org
      script: npx @parameter1/base-cms-website-deployment-tool deploy isc.hub.heart.org websites
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-njflm]

    # - stage: staging
    #   name: isc.hub.heart.org
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy isc.hub.heart.org websites
    #   install: skip
    #   env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: minexpo.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy minexpo.com tauron-websites
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-njflm]

    # - stage: staging
    #   name: minexpo.com
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy minexpo.com tauron-websites
    #   install: skip
    #   env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: imex.ascendmedia.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy imex.ascendmedia.com websites
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-njflm]

    # - stage: staging
    #   name: imex.ascendmedia.com
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy imex.ascendmedia.com websites
    #   install: skip
    #   env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: bulletin.entnet.org
      script: npx @parameter1/base-cms-website-deployment-tool deploy bulletin.entnet.org websites
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-njflm]

    # - stage: staging
    #   name: bulletin.entnet.org
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy bulletin.entnet.org websites
    #   install: skip
    #   env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-rc5kp]

    #############################
    ### ^^^ ADD SITES HERE ^^^ ##
    #############################

    - stage: production-finished
      name: Deployment Finished
      script: npx @parameter1/base-cms-website-deployment-tool notify-finished
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-njflm]

    # - stage: staging-finished
    #   name: Deployment Finished
    #   script: npx @parameter1/base-cms-website-deployment-tool notify-finished
    #   install: skip
    #   env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]
